name: Polling and Publish AMDSMI

on:
  schedule:
    # Runs at 05:00 UTC every day
    - cron:  '0 5 * * *'
  workflow_dispatch: # allow for manual trigger

jobs:
  polling_amdsmi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Git configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.9'
      
      - name: Fix and publish, iff there exists a tag in rocm/amdsmi that is not here.
        run: |
            chmod +x ./scripts/checkout_and_push_tag.sh
            ./scripts/checkout_and_push_tag.sh