name: Polling and Publish AMDSMI

on:
  schedule:
    # Runs at 05:00 UTC every day
    - cron:  '0 5 * * *'
  workflow_dispatch: # allow for manual trigger

jobs:
  polling_amdsmi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Git configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fix and publish, iff there exists a tag in rocm/amdsmi that is not here.
        run: |
            chmod +x ./scripts/checkout_and_push_tag.sh
            ./scripts/checkout_and_push_tag.sh || true  # Avoid failing the workflow on exit code 1

            if [ $? -eq 0 ]; then
              echo "::set-output name=tag_published::true"
            else
              echo "::set-output name=tag_published::false"
            fi

  publish:
    runs-on: ubuntu-latest
    if: ${{ needs.polling_amdsmi.outputs.tag_published == 'true' }}  # Run only if a new tag was published
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install build twine

    - name: Build distribution
      working-directory: ./py-interface
      run: |
        python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_API_KEY }}
      working-directory: ./py-interface
      run: |
        twine upload dist/*